name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  gcc_test:
    runs-on: ubuntu-latest

    steps:
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    - run: arm-none-eabi-gcc -v
