name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  gcc_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    - run: cmake -S$GITHUB_WORKSPACE -Bbuild -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE
